### ISSUE TITLE
Docker builds

### ISSUE THREAD

**Issue by JackDunnCodes** [LA1TV/Website-Backend#8]
Use what we did in LA1TV/Website-Frontend#15 to make beta and stable builds

**Comment by SuperNinja-4965** [comment]
If a docker hub repo is created the workflow from the frontend can just have its url updated and then merged as it should be 100% compatible.

**Comment by JackDunnCodes** [comment]
Feel free to go ahead and do it, I've just created https://hub.docker.com/r/la1tv/website-backend and will add the same github secrets
